
CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR2(50) UNIQUE NOT NULL,
    clave VARCHAR2(200) NOT NULL,
    nombre VARCHAR2(50),
    apellido VARCHAR2(50),
    fecha_nacimiento DATE,
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    tipo VARCHAR2(20)
);

- Pacientes
CREATE TABLE paciente (
    id NUMBER PRIMARY KEY,
    comuna VARCHAR2(50),
    fecha_primera_visita DATE,
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (id) REFERENCES usuario(id)
);

-- Médicos
CREATE TABLE medico (
    id NUMBER PRIMARY KEY,
    especialidad VARCHAR2(50),
    horario_atencion VARCHAR2(50),
    fecha_ingreso DATE,
    CONSTRAINT fk_medico_usuario FOREIGN KEY (id) REFERENCES usuario(id)
);

- Consultas
CREATE TABLE consulta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER,
    id_medico NUMBER,
    id_receta NUMBER,
    fecha DATE,
    comentarios VARCHAR2(200),
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id),
    CONSTRAINT fk_consulta_medico FOREIGN KEY (id_medico) REFERENCES medico(id)
);

- Recetas
CREATE TABLE receta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER,
    id_medico NUMBER,
    descripcion VARCHAR2(200),
    CONSTRAINT fk_receta_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id),
    CONSTRAINT fk_receta_medico FOREIGN KEY (id_medico) REFERENCES medico(id)
);

- Agenda
CREATE TABLE agenda (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente NUMBER,
    id_medico NUMBER,
    fecha_consulta DATE,
    estado VARCHAR2(20),
    CONSTRAINT fk_agenda_paciente FOREIGN KEY (id_paciente) REFERENCES paciente(id),
    CONSTRAINT fk_agenda_medico FOREIGN KEY (id_medico) REFERENCES medico(id)
);

- Insumos
CREATE TABLE insumos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50),
    tipo VARCHAR2(50),
    stock NUMBER
);
